### ISSUE TITLE
Review 1 - changes needed

### ISSUE THREAD

**Issue by tmaryon** [JosephGreenburg/Joes-JavaScript-Projects#2]
# Review 1

### Next Steps:

- [x] move all CSS into a `<style>` tag
- [x] move all JavaScript into `<script>` tag(s) in the `<head>`, near `</body>`, or both
- [x] get the functionality working on JavaScript, including
  - [x] use array elements
  - [x] fix function that adds new first/last name entries to the names array
  - [x] figure out why your submit does not work
- [x] apply KISS/YAGNI/DRY principles, wherever possible

**Comment by JosephGreenburg** [comment]
The CSS is within the head in a <style> tag.

I could not get the Javascript to work as expected when moving components in the <head>. Can you show me which parts of the JS can work within that tag?

I have created an alternate array that captures the full named entered instead of the array of objects.

The first/last name entries are already being pushed to the arrays

The submit button is working with `click` and `keyup`/"Enter"
